# Generated by Django 5.1.15 on 2026-01-05 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_intents", models.JSONField(blank=True, default=list)),
                ("financial_goals", models.JSONField(blank=True, default=list)),
                ("has_student_loans", models.BooleanField(default=False)),
                ("has_credit_card_debt", models.BooleanField(default=False)),
                ("has_car_payments", models.BooleanField(default=False)),
                (
                    "housing_status",
                    models.CharField(
                        choices=[
                            ("RENT", "Rent"),
                            ("OWN", "Own"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                (
                    "onboarding_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
