# Generated by Django 5.1.15 on 2026-01-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_financial_goals_userprofile_goal_intents_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="goal_intents",
            new_name="financial_goals",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="onboarding_completed",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="plaid_linked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="step1_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="step2_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="step3_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
