# Generated by Django 5.1.15 on 2026-01-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_goal_intents_userprofile_financial_goals_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="housing_status",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="has_mortgage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pays_rent",
            field=models.BooleanField(default=False),
        ),
    ]
