# Generated by Django 5.2.2 on 2025-12-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("rent", "Rent"),
                    ("groceries", "Groceries"),
                    ("restaurants", "Restaurants"),
                    ("utilities", "Utilities"),
                    ("transport", "Transport"),
                    ("entertainment", "Entertainment"),
                    ("shopping", "Shopping"),
                    ("health", "Health"),
                    ("savings", "Savings"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Positive or negative relative to the account",
                max_digits=10,
            ),
        ),
    ]
