# Generated by Django 5.1.15 on 2025-12-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction_category_alter_transaction_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_type",
        ),
        migrations.AddField(
            model_name="transaction",
            name="currency_code",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Signed amount relative to the account",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("rent", "Rent"),
                    ("groceries", "Groceries"),
                    ("restaurants", "Restaurants"),
                    ("utilities", "Utilities"),
                    ("transport", "Transport"),
                    ("entertainment", "Entertainment"),
                    ("shopping", "Shopping"),
                    ("health", "Health"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
