# Generated by Django 5.1.15 on 2025-12-19 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_remove_transaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="external_transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Provider-specific transaction ID (e.g. Plaid)",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="pending",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="plaid_category_detailed",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="plaid_category_primary",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Canonical category set by classification logic",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="related_transaction",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked transfer (set later, never during ingestion)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.transaction",
            ),
        ),
    ]
