# Generated by Django 5.1.15 on 2025-12-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_transaction_external_transaction_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="external_transaction_id",
            field=models.CharField(
                default=1,
                help_text="Provider-specific transaction ID (e.g. Plaid)",
                max_length=128,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
