# Generated by Django 5.1.15 on 2025-12-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_transaction_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="external_transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Provider-specific transaction ID (e.g. Plaid)",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
    ]
