# Generated by Django 5.1.15 on 2026-01-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_alter_transaction_external_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Signed amount: inflow positive, outflow negative (normalized at ingestion)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="external_transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Provider-specific transaction ID (e.g. Plaid)",
                max_length=128,
                null=True,
            ),
        ),
    ]
