# Generated by Django 5.1.15 on 2026-01-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_account_unique_external_account_per_user_and_more"),
        ("transactions", "0007_alter_transaction_amount_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("account", "external_transaction_id"),
                name="unique_external_tx_per_account",
            ),
        ),
    ]
