# Generated by Django 5.1.15 on 2025-12-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_user_alter_account_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="category",
        ),
        migrations.RemoveField(
            model_name="account",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="account",
            name="is_active",
        ),
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("checking", "Checking"),
                    ("savings", "Savings"),
                    ("credit card", "Credit Card"),
                    ("loan", "Loan"),
                    ("investment", "Investment"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="balance_available",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="balance_current",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="account",
            name="credit_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="currency_code",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="account",
            name="data_source",
            field=models.CharField(
                default="manual", help_text="manual | plaid | other", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="external_account_id",
            field=models.CharField(
                blank=True,
                help_text="Provider-specific account ID (e.g. Plaid)",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="institution_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="mask",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
