# Generated by Django 5.1.15 on 2026-01-05 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_account_plaid_item_and_more"),
        ("plaid_link", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="unique_external_account_per_user",
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_account_id__isnull", False)),
                fields=("user", "external_account_id"),
                name="unique_external_account_per_user_nonnull",
            ),
        ),
    ]
